server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hanium_pilot
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
graphiql:
  mapping: /ui
graphql :
  servlet:
    mapping: /service