spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todoList
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: ture
        format_sql: ture

logging:
  level:
    org.hibernate.SQL: debug