spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa/h2/bin/pilot-todo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true