spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: slowdelivery22@gmail.com
    password: abc123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true