server:
  port: 9001  # 9000번 포트로 실행

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/9key
    username: 9key
    password: 9key
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true