spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      format_sql: true
    show-sql: true
    generate-ddl: true

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace